backend_maintest:
    path:     /routingapp/main
    defaults: 
        _controller: BugBusterRoutingappBundle:Backend:bemain
        _scope: backend
        _token_check: true
        _custom_backend_view: true
        _backend_module: bemain

backend_details:
    path:     /routingapp/details
    defaults: 
        _controller: BugBusterRoutingappBundle:Backend:details
        _scope: backend
        _token_check: true

frontend_demo:
    path:     /routingapp_fe/demo/{height}/{width}
    defaults: 
        _controller: BugBusterRoutingappBundle:Frontend:demo
        _scope: frontend
        _token_check: false
        height: 0
        width:  0
    requirements:
        height: '\d+'
        width:  '\d+'

frontend_demo_remove_trailing_slash:
    path:     /routingapp_fe/demo/{url}
    defaults:
        _controller: BugBusterRoutingappBundle:Frontend:removeTrailingSlash
        _scope: frontend
        _token_check: false
    requirements:
        url: .*/$
    methods: [GET]
